//  productsjs
import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router';
import Header from "../../component/Header";
import Footer from "../../component/Footer";

export default function Products() {
    const { query: { id } } = useRouter();

    return (
        <div className="products">
            <Head>
                <title>Shopping App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header headerTitle="Shopping App" logoURL="/" cartURL="/cart" />
            <main className="container">
                <p>ID: {id}</p>
            </main>
            <Footer />
        </div>
    );
}