//  productsjs
import React, { useState, useEffect } from 'react';
import Head from "next/head";
import { useRouter } from 'next/router';
import Header from "../../component/Header";
import Footer from "../../component/Footer";

export default function Products() {
    const { query: { id } } = useRouter();
    const [ productData, setProductData ] = useState([]);

    const fetchData = async(url, params, callback) => {
        const settings = {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(params)
        };

        const response = await fetch(url, settings);
        const data = await response.json();
        
        callback(data);
    }

    useEffect(() => {
        fetchData('/api/getproducts', { 'productid': id }, (data) => {
            setProductData(data.message);
        });
    }, [id]);

    useEffect(() => {
        console.log(productData[0]);
    }, [productData]);

    return (
        <div className="products">
            <Head>
                <title>Shopping App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header headerTitle="Shopping App" logoURL="/" cartURL="/cart" />
            <main className="container">
                <p>ID: {id}</p>
            </main>
            <Footer />
        </div>
    );
}