import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect } from 'react';
import Header from '../component/Header';
import Jumboltron from '../component/Jumboltron';
import Footer from '../component/Footer';

export default function Home() {

  useEffect(() => {
    fetch('/api').then(response => response.json()).then(data => console.log(data));
  }, []);

  return (
    <div>
      <Head>
        <title>Shopping App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerTitle='Shopping App' logoURL="/" cartURL="/cart"  />
      <Jumboltron title="Shop By Category" subTitle={ "Shop with over 10 products listed." } />
      <main>

      </main>
      <Footer />
    </div>
  )
}
